- id: offensiveboar
  name: OffensiveBoar
  description: Detect secrets in your data with OffensiveBoar.
  entry: offensiveboar git file://. --since-commit HEAD --results=verified --fail
  language: golang
  pass_filenames: false
