package defaults

import (
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/abuseipdb"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/abyssale"
	accuweatherv1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/accuweather/v1"
	accuweatherv2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/accuweather/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/adafruitio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/adzuna"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/aeroworkflow"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/agora"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/aha"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/airbrakeprojectkey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/airbrakeuserkey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/airship"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/airtableoauth"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/airtablepersonalaccesstoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/airvisual"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/aiven"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/alchemy"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/alegra"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/aletheiaapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/algoliaadminkey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/alibaba"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/alienvault"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/allsports"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/amadeus"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ambee"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/amplitudeapikey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/anthropic"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/anypoint"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/apacta"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/api2cart"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/apideck"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/apiflash"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/apifonica"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/apify"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/apilayer"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/apimatic"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/apimetrics"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/apitemplate"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/appcues"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/appfollow"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/appointedd"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/appoptics"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/appsynergy"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/apptivo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/artifactory"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/artsy"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/asanaoauth"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/asanapersonalaccesstoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/assemblyai"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/atera"
	atlassianv1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/atlassian/v1"
	atlassianv2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/atlassian/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/audd"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/auth0managementapitoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/auth0oauth"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/autodesk"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/autoklose"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/autopilot"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/avazapersonalaccesstoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/aviationstack"
	aws_access_keys "github.com/etyvrox/offensiveboar/v3/pkg/detectors/aws/access_keys"
	aws_session_keys "github.com/etyvrox/offensiveboar/v3/pkg/detectors/aws/session_keys"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/axonaut"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/aylien"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ayrshare"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/azure_batch"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/azure_cosmosdb"
	azure_entra_refreshtoken "github.com/etyvrox/offensiveboar/v3/pkg/detectors/azure_entra/refreshtoken"
	azure_entra_serviceprincipal_v1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/azure_entra/serviceprincipal/v1"
	azure_entra_serviceprincipal_v2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/azure_entra/serviceprincipal/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/azure_openai"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/azure_storage"
	azurerepositorykey "github.com/etyvrox/offensiveboar/v3/pkg/detectors/azureapimanagement/repositorykey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/azureapimanagementsubscriptionkey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/azureappconfigconnectionstring"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/azurecontainerregistry"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/azuredevopspersonalaccesstoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/azuredirectmanagementkey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/azuresastoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/azuresearchadminkey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/azuresearchquerykey"
	bannerbearv1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/bannerbear/v1"
	bannerbearv2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/bannerbear/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/baremetrics"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/beamer"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/beebole"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/besttime"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/betterstack"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/billomat"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/bingsubscriptionkey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/bitbar"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/bitbucketapppassword"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/bitcoinaverage"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/bitfinex"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/bitlyaccesstoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/bitmex"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/blazemeter"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/blitapp"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/blogger"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/bombbomb"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/boostnote"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/borgbase"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/box"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/boxoauth"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/braintreepayments"
	brandfetchv1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/brandfetch/v1"
	brandfetchv2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/brandfetch/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/browserstack"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/browshot"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/bscscan"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/buddyns"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/budibase"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/bugherd"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/bugsnag"
	buildKitev1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/buildkite/v1"
	buildKitev2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/buildkite/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/bulbul"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/bulksms"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/buttercms"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/caflou"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/calendarific"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/calendlyapikey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/calorieninja"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/campayn"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cannyio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/capsulecrm"
	captainDataV1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/captaindata/v1"
	captainDataV2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/captaindata/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/carboninterface"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cashboard"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/caspio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/censys"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/centralstationcrm"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cexio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/chartmogul"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/chatbot"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/chatfule"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/checio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/checklyhq"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/checkout"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/checkvist"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cicero"
	circleciV1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/circleci/v1"
	circleciV2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/circleci/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/clarifai"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/clearbit"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/clickhelp"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/clicksendsms"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/clickuppersonaltoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cliengo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/clientary"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/clinchpad"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/clockify"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/clockworksms"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/closecrm"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cloudconvert"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cloudelements"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cloudflareapitoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cloudflarecakey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cloudflareglobalapikey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cloudimage"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cloudmersive"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cloudplan"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cloudsmith"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cloverly"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cloze"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/clustdoc"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/coda"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/codacy"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/codeclimate"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/codemagic"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/codequiry"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/coinapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/coinbase"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/coinlayer"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/coinlib"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/collect2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/column"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/commercejs"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/commodities"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/companyhub"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/confluent"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/contentfulpersonalaccesstoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/conversiontools"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/convertapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/convertkit"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/convier"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/copper"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/couchbase"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/custom"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/countrylayer"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/courier"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/coveralls"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/craftmypdf"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/crowdin"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/cryptocompare"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/currencycloud"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/currencyfreaks"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/currencylayer"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/currencyscoop"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/currentsapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/customerguru"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/customerio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/d7network"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/dandelion"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/dareboost"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/databox"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/databrickstoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/datadogtoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/datagov"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/deepai"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/deepgram"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/deepseek"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/delighted"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/demio"
	denodeploy "github.com/etyvrox/offensiveboar/v3/pkg/detectors/deno"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/deputy"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/detectify"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/detectlanguage"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/dfuse"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/diffbot"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/diggernaut"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/digitaloceantoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/digitaloceanv2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/discordbottoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/discordwebhook"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/disqus"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ditto"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/dnscheck"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/docker"
	dockerhubv1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/dockerhub/v1"
	dockerhubv2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/dockerhub/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/docparser"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/documo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/docusign"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/doppler"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/dotdigital"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/dovico"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/dronahq"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/droneci"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/dropbox"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/duply"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/dwolla"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/dynalist"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/dyspatch"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/eagleeyenetworks"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/easyinsight"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ecostruxureit"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/edamam"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/edenai"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/eightxeight"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/elasticemail"
	elevenlabsv1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/elevenlabs/v1"
	elevenlabsv2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/elevenlabs/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/enablex"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/endorlabs"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/enigma"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/envoyapikey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/eraser"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/etherscan"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ethplorer"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/eventbrite"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/everhour"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/exchangerateapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/exchangeratesapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/exportsdk"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/extractorapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/facebookoauth"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/faceplusplus"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/fastforex"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/fastlypersonaltoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/feedier"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/fetchrss"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/fibery"
	figmapersonalaccesstokenv1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/figmapersonalaccesstoken/v1"
	figmapersonalaccesstokenv2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/figmapersonalaccesstoken/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/fileio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/finage"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/financialmodelingprep"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/findl"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/finnhub"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/fixerio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/flatio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/fleetbase"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/flexport"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/flickr"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/flightapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/flightlabs"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/flightstats"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/float"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/flowflu"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/flutterwave"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/flyio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/fmfw"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/formbucket"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/formcraft"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/formio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/formsite"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/foursquare"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/frameio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/freshbooks"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/freshdesk"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/front"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ftp"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/fulcrum"
	fullstoryv1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/fullstory/v1"
	fullstoryv2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/fullstory/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/fxmarket"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/gcp"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/gcpapplicationdefaultcredentials"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/geckoboard"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/gemini"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/gengo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/geoapify"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/geocode"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/geocodify"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/geocodio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/geoipifi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/getgeoapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/getgist"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/getresponse"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/getsandbox"
	githubv1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/github/v1"
	githubv2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/github/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/github_oauth2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/githubapp"
	gitlabv1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/gitlab/v1"
	gitlabv2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/gitlab/v2"
	gitlabv3 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/gitlab/v3"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/gitter"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/glassnode"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/gocanvas"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/gocardless"
	godaddyv1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/godaddy/v1"
	godaddyv2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/godaddy/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/goodday"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/googleoauth2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/grafana"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/grafanaserviceaccount"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/graphcms"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/graphhopper"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/groovehq"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/groq"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/gtmetrix"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/guardianapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/gumroad"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/gyazo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/happyscribe"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/harness"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/harvest"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/hashicorpvaultauth"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/hasura"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/hellosign"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/helpcrunch"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/helpscout"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/hereapi"
	heroku_v1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/heroku/v1"
	heroku_v2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/heroku/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/hiveage"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/holidayapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/holistic"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/honeycomb"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/host"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/html2pdf"
	hubspot_apikey_v1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/hubspot_apikey/v1"
	hubspot_apikey_v2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/hubspot_apikey/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/huggingface"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/humanity"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/hunter"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/hybiscus"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/hypertrack"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/iconfinder"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/iexapis"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/iexcloud"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/imagekit"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/imagga"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/impala"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/infura"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/insightly"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/instabot"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/instamojo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/intercom"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/interseller"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/intra42"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/intrinio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/invoiceocean"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ip2location"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ipapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ipgeolocation"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ipinfodb"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ipquality"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ipstack"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/jdbc"
	jiratokenv1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/jiratoken/v1"
	jiratokenv2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/jiratoken/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/jotform"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/jumpcloud"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/jupiterone"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/juro"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/jwt"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/kanban"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/kanbantool"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/karmacrm"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/keenio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/kickbox"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/klaviyo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/klipfolio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/knapsackpro"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/kontent"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/kraken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/kucoin"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/kylas"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/langfuse"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/langsmith"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/languagelayer"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/larksuite"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/larksuiteapikey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/launchdarkly"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ldap"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/leadfeeder"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/lemlist"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/lemonsqueezy"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/lendflow"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/lessannoyingcrm"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/lexigram"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/linearapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/linenotify"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/linkpreview"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/liveagent"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/livestorm"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/loadmill"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/locationiq"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/loggly"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/loginradius"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/logzio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/lokalisetoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/loyverse"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/lunchmoney"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/luno"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/madkudu"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/magicbell"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mailboxlayer"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mailchimp"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mailerlite"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mailgun"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mailjetbasicauth"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mailjetsms"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mailmodo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mailsac"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mandrill"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mapbox"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mapquest"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/marketstack"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mattermostpersonaltoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mavenlink"
	maxmindlicensev1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/maxmindlicense/v1"
	maxmindlicensev2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/maxmindlicense/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/meaningcloud"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mediastack"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/meistertask"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/meraki"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mesibo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/messagebird"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/metaapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/metabase"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/metrilo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/microsoftteamswebhook"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mindmeister"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/miro"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mite"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mixmax"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mockaroo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/moderation"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/monday"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mongodb"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/monkeylearn"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/moonclerk"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/moosend"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/moralis"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mrticktock"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/mux"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/myfreshworks"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/myintervals"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/nethunt"
	netlifyv1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/netlify/v1"
	netlifyv2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/netlify/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/netsuite"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/neutrinoapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/newrelicpersonalapikey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/newsapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/newscatcher"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/nexmoapikey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/nftport"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ngc"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ngrok"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/nicereply"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/nightfall"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/nimble"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/noticeable"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/notion"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/nozbeteams"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/npmtoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/npmtokenv2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/nugetapikey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/numverify"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/nutritionix"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/nvapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/nylas"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/oanda"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/okta"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/omnisend"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/onedesk"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/onelogin"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/onepagecrm"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/onesignal"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/onfleet"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/oopspam"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/openai"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/opencagedata"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/openuv"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/openvpn"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/openweather"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/opsgenie"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/optimizely"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/overloop"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/owlbot"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/packagecloud"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pagarme"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pagerdutyapikey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pandadoc"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pandascore"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/paperform"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/paralleldots"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/parsehub"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/parsers"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/parseur"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/partnerstack"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pastebin"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/paydirtapp"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/paymoapp"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/paymongo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/paypaloauth"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/paystack"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pdflayer"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pdfshift"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/peopledatalabs"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pepipost"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/percy"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/photoroom"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/phraseaccesstoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pinata"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pipedream"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pipedrive"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pivotaltracker"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pixabay"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/plaidkey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/planetscale"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/planetscaledb"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/planviewleankit"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/planyo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/plivo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/podio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pollsapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/poloniex"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/polygon"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/portainer"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/portainertoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/positionstack"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/postageapp"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/postbacks"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/postgres"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/posthog"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/postman"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/postmark"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/powrbot"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/prefect"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/privacy"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/privatekey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/prodpad"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/prospectcrm"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/protocolsio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/proxycrawl"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pubnubpublishkey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pubnubsubscriptionkey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pulumi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/purestake"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pushbulletapikey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pusherchannelkey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/pypi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/qase"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/qualaroo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/qubole"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/rabbitmq"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/railwayapp"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ramp"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/rapidapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/rawg"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/razorpay"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/reachmail"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/readme"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/reallysimplesystems"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/rebrandly"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/rechargepayments"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/redis"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/refiner"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/rentman"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/repairshopr"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/replicate"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/replyio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/requestfinance"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/restpackhtmltopdfapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/restpackscreenshotapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/revampcrm"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ringcentral"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ritekit"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/roaring"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/robinhoodcrypto"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/rocketreach"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/rootly"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/route4me"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/rownd"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/rubygems"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/runrunit"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/saladcloudapikey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/salesblink"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/salescookie"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/salesflare"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/salesforce"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/salesforceoauth2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/salesforcerefreshtoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/salesmate"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sanity"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/satismeterprojectkey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/satismeterwritekey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/saucelabs"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/scalewaykey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/scalr"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/scrapeowl"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/scraperapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/scraperbox"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/scrapestack"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/scrapfly"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/scrapingant"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/scrapingbee"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/screenshotapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/screenshotlayer"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/scrutinizerci"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/securitytrails"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/segmentapikey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/selectpdf"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/semaphore"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sendbird"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sendbirdorganizationapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sendgrid"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sendinbluev2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sentryorgtoken"
	sentrytokenv1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/sentrytoken/v1"
	sentrytokenv2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/sentrytoken/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/serphouse"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/serpstack"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sheety"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sherpadesk"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/shipday"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/shodankey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/shopify"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/shortcut"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/shotstack"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/shutterstock"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/shutterstockoauth"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/signable"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/signalwire"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/signaturit"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/signupgenius"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sigopt"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/simfin"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/simplesat"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/simplynoted"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/simvoly"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sinchmessage"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sirv"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/siteleaf"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/skrappio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/skybiometry"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/slack"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/slackwebhook"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/smartsheets"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/smartystreets"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/smooch"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/snipcart"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/snowflake"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/snykkey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sonarcloud"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sourcegraph"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sourcegraphcody"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/speechtextai"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/splunkobservabilitytoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/spoonacular"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sportsmonk"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sqlserver"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/square"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/squareapp"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/squarespace"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/squareup"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sslmate"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/statuscake"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/statuspage"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/statuspal"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/stitchdata"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/stockdata"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/storecove"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/stormboard"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/stormglass"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/storyblok"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/storyblokpersonalaccesstoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/storychief"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/strava"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/streak"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/stripe"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/stripepaymentintent"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/stripo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/stytch"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sugester"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/sumologickey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/supabasetoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/supernotesapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/surveyanyplace"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/surveybot"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/surveysparrow"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/survicate"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/swell"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/swiftype"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/tableau"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/tailscale"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/tallyfy"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/tatumio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/taxjar"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/teamgate"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/teamworkcrm"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/teamworkdesk"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/teamworkspaces"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/technicalanalysisapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/tefter"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/telegrambottoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/teletype"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/telnyx"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/terraformcloudpersonaltoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/testingbot"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/textmagic"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/theoddsapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/thinkific"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/thousandeyes"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ticketmaster"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/tickettailor"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/tiingo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/timecamp"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/timezoneapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/tineswebhook"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/tmetric"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/todoist"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/tokeet"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/tomorrowio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/tomtom"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/tradier"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/transferwise"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/travelpayouts"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/travisci"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/trelloapikey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/offensiveboarenterprise"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/twelvedata"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/twilio"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/twilioapikey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/twist"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/twitch"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/twitchaccesstoken"
	twitterv1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/twitter/v1"
	twitterv2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/twitter/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/twitterconsumerkey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/tyntec"
	typeformv1 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/typeform/v1"
	typeformv2 "github.com/etyvrox/offensiveboar/v3/pkg/detectors/typeform/v2"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/typetalk"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/ubidots"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/uclassify"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/unifyid"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/unplugg"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/unsplash"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/upcdatabase"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/uplead"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/uploadcare"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/uptimerobot"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/upwave"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/uri"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/urlscan"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/userflow"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/userstack"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/vagrantcloudpersonaltoken"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/vatlayer"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/vbout"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/vercel"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/verifier"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/verimail"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/veriphone"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/versioneye"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/viewneo"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/virustotal"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/visualcrossing"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/voiceflow"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/voicegain"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/voodoosms"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/vouchery"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/vpnapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/vultrapikey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/vyte"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/walkscore"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/weatherbit"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/weatherstack"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/web3storage"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/webex"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/webexbot"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/webflow"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/webscraper"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/webscraping"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/websitepulse"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/weightsandbiases"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/whoxy"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/wistia"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/wiz"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/worksnaps"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/workstack"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/worldcoinindex"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/worldweather"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/wrike"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/xai"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/yandex"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/yelp"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/youneedabudget"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/yousign"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/youtubeapikey"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/zendeskapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/zenkitapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/zenrows"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/zenscrape"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/zenserp"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/zeplin"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/zerobounce"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/zerotier"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/zipapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/zipbooks"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/zipcodeapi"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/zipcodebase"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/zohocrm"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/zonkafeedback"
	"github.com/etyvrox/offensiveboar/v3/pkg/detectors/zulipchat"
	"github.com/etyvrox/offensiveboar/v3/pkg/pb/detectorspb"
)

func buildDetectorList() []detectors.Detector {
	return []detectors.Detector{
		&abyssale.Scanner{},
		// &abstract.Scanner{},
		&abuseipdb.Scanner{},
		&accuweatherv1.Scanner{},
		&accuweatherv2.Scanner{},
		&adafruitio.Scanner{},
		// &adobeio.Scanner{},
		&adzuna.Scanner{},
		&aeroworkflow.Scanner{},
		&agora.Scanner{},
		&aha.Scanner{},
		&airbrakeprojectkey.Scanner{},
		&airbrakeuserkey.Scanner{},
		&airship.Scanner{},
		&airtableoauth.Scanner{},
		&airtablepersonalaccesstoken.Scanner{},
		&airvisual.Scanner{},
		&aiven.Scanner{},
		&alchemy.Scanner{},
		// The service currently has blocked requests with a "OffensiveBoar" UserAgent.
		// &alconost.Scanner{},
		&alegra.Scanner{},
		&aletheiaapi.Scanner{},
		&algoliaadminkey.Scanner{},
		&alibaba.Scanner{},
		&alienvault.Scanner{},
		&allsports.Scanner{},
		&amadeus.Scanner{},
		&ambee.Scanner{},
		&amplitudeapikey.Scanner{},
		&anthropic.Scanner{},
		&anypoint.Scanner{},
		&apacta.Scanner{},
		&api2cart.Scanner{},
		&apideck.Scanner{},
		&apiflash.Scanner{},
		&apifonica.Scanner{},
		&apify.Scanner{},
		&apilayer.Scanner{},
		&apimatic.Scanner{},
		&apimetrics.Scanner{},
		&apitemplate.Scanner{},
		// &apollo.Scanner{},
		&appcues.Scanner{},
		&appfollow.Scanner{},
		&appointedd.Scanner{},
		&appoptics.Scanner{},
		&appsynergy.Scanner{},
		&apptivo.Scanner{},
		&artifactory.Scanner{},
		&artsy.Scanner{},
		&asanaoauth.Scanner{},
		&asanapersonalaccesstoken.Scanner{},
		&assemblyai.Scanner{},
		&atera.Scanner{},
		&atlassianv1.Scanner{},
		&atlassianv2.Scanner{},
		&audd.Scanner{},
		&auth0managementapitoken.Scanner{},
		&auth0oauth.Scanner{},
		&autodesk.Scanner{},
		&autoklose.Scanner{},
		&autopilot.Scanner{},
		&avazapersonalaccesstoken.Scanner{},
		&aviationstack.Scanner{},
		aws_access_keys.New(),
		aws_session_keys.New(),
		&axonaut.Scanner{},
		&aylien.Scanner{},
		&ayrshare.Scanner{},
		&azureapimanagementsubscriptionkey.Scanner{},
		&azure_entra_refreshtoken.Scanner{},
		&azure_entra_serviceprincipal_v1.Scanner{},
		&azure_entra_serviceprincipal_v2.Scanner{},
		&azure_batch.Scanner{},
		&azureappconfigconnectionstring.Scanner{},
		&azure_cosmosdb.Scanner{},
		&azurecontainerregistry.Scanner{},
		&azuredevopspersonalaccesstoken.Scanner{},
		&azuredirectmanagementkey.Scanner{},
		// &azurefunctionkey.Scanner{}, // detector is throwing some FPs
		&azure_openai.Scanner{},
		&azuresastoken.Scanner{},
		&azuresearchadminkey.Scanner{},
		&azuresearchquerykey.Scanner{},
		&azure_storage.Scanner{},
		&azurerepositorykey.Scanner{},
		&bannerbearv1.Scanner{},
		&bannerbearv2.Scanner{},
		&baremetrics.Scanner{},
		&beamer.Scanner{},
		&beebole.Scanner{},
		// Besnappy appears to be abandoned. The domain has expired. API returns 200 OK for all secrets causing FPs
		// &besnappy.Scanner{},
		&besttime.Scanner{},
		&betterstack.Scanner{},
		&billomat.Scanner{},
		&bingsubscriptionkey.Scanner{},
		&bitbar.Scanner{},
		&bitbucketapppassword.Scanner{},
		&bitcoinaverage.Scanner{},
		&bitfinex.Scanner{},
		&bitlyaccesstoken.Scanner{},
		&bitmex.Scanner{},
		&blazemeter.Scanner{},
		&blitapp.Scanner{},
		// &blocknative.Scanner{}, // temporary disabled due to API issue
		&blogger.Scanner{},
		&bombbomb.Scanner{},
		&boostnote.Scanner{},
		&borgbase.Scanner{},
		&box.Scanner{},
		&boxoauth.Scanner{},
		&braintreepayments.Scanner{},
		&brandfetchv1.Scanner{},
		&brandfetchv2.Scanner{},
		&browserstack.Scanner{},
		&browshot.Scanner{},
		&bscscan.Scanner{},
		&buddyns.Scanner{},
		&budibase.Scanner{},
		&bugherd.Scanner{},
		&bugsnag.Scanner{},
		&buildKitev1.Scanner{},
		&buildKitev2.Scanner{},
		&bulbul.Scanner{},
		&bulksms.Scanner{},
		&buttercms.Scanner{},
		&caflou.Scanner{},
		&calendarific.Scanner{},
		&calendlyapikey.Scanner{},
		&calorieninja.Scanner{},
		&campayn.Scanner{},
		&cannyio.Scanner{},
		&capsulecrm.Scanner{},
		&captainDataV1.Scanner{},
		&captainDataV2.Scanner{},
		&carboninterface.Scanner{},
		&cashboard.Scanner{},
		&caspio.Scanner{},
		&censys.Scanner{},
		&centralstationcrm.Scanner{},
		&cexio.Scanner{},
		&chartmogul.Scanner{},
		&chatbot.Scanner{},
		&chatfule.Scanner{},
		&checio.Scanner{},
		&checklyhq.Scanner{},
		&checkout.Scanner{},
		&checkvist.Scanner{},
		&cicero.Scanner{},
		&circleciV1.Scanner{},
		&circleciV2.Scanner{},
		&clarifai.Scanner{},
		&clearbit.Scanner{},
		&clickhelp.Scanner{},
		&clicksendsms.Scanner{},
		&clickuppersonaltoken.Scanner{},
		&cliengo.Scanner{},
		&clientary.Scanner{},
		&clinchpad.Scanner{},
		&clockify.Scanner{},
		&clockworksms.Scanner{},
		&closecrm.Scanner{},
		&cloudconvert.Scanner{},
		&cloudelements.Scanner{},
		&cloudflareapitoken.Scanner{},
		&cloudflarecakey.Scanner{},
		&cloudflareglobalapikey.Scanner{},
		&cloudimage.Scanner{},
		&cloudmersive.Scanner{},
		&cloudplan.Scanner{},
		&cloudsmith.Scanner{},
		&cloverly.Scanner{},
		&cloze.Scanner{},
		&clustdoc.Scanner{},
		&coda.Scanner{},
		&codacy.Scanner{},
		&codeclimate.Scanner{},
		&codemagic.Scanner{},
		&codequiry.Scanner{},
		&coinapi.Scanner{},
		&coinbase.Scanner{},
		&coinlayer.Scanner{},
		&coinlib.Scanner{},
		&collect2.Scanner{},
		&column.Scanner{},
		&commercejs.Scanner{},
		&commodities.Scanner{},
		&companyhub.Scanner{},
		&confluent.Scanner{},
		&contentfulpersonalaccesstoken.Scanner{},
		&conversiontools.Scanner{},
		&convertapi.Scanner{},
		&convertkit.Scanner{},
		&convier.Scanner{},
		&copper.Scanner{},
		&couchbase.Scanner{},
		&custom.Scanner{},
		&countrylayer.Scanner{},
		&courier.Scanner{},
		&coveralls.Scanner{},
		&craftmypdf.Scanner{},
		&crowdin.Scanner{},
		&cryptocompare.Scanner{},
		&currencycloud.Scanner{},
		&currencyfreaks.Scanner{},
		&currencylayer.Scanner{},
		&currencyscoop.Scanner{},
		&currentsapi.Scanner{},
		&customerguru.Scanner{},
		&customerio.Scanner{},
		&d7network.Scanner{},
		// &dailyco.Scanner{},
		&dandelion.Scanner{},
		&dareboost.Scanner{},
		&databox.Scanner{},
		&databrickstoken.Scanner{},
		&datadogtoken.Scanner{},
		&datagov.Scanner{},
		// &debounce.Scanner{},
		&deepai.Scanner{},
		&deepgram.Scanner{},
		&deepseek.Scanner{},
		&delighted.Scanner{},
		&demio.Scanner{},
		&denodeploy.Scanner{},
		&deputy.Scanner{},
		&detectify.Scanner{},
		&detectlanguage.Scanner{},
		&dfuse.Scanner{},
		&diffbot.Scanner{},
		&diggernaut.Scanner{},
		&digitaloceantoken.Scanner{},
		&digitaloceanv2.Scanner{},
		&discordbottoken.Scanner{},
		&discordwebhook.Scanner{},
		&disqus.Scanner{},
		&ditto.Scanner{},
		&dnscheck.Scanner{},
		&docker.Scanner{},
		&dockerhubv1.Scanner{},
		&dockerhubv2.Scanner{},
		&docparser.Scanner{},
		&documo.Scanner{},
		&docusign.Scanner{},
		&doppler.Scanner{},
		&dotdigital.Scanner{},
		&dovico.Scanner{},
		&dronahq.Scanner{},
		&droneci.Scanner{},
		&dropbox.Scanner{},
		&duply.Scanner{},
		&dwolla.Scanner{},
		&dynalist.Scanner{},
		&dyspatch.Scanner{},
		&eagleeyenetworks.Scanner{},
		&easyinsight.Scanner{},
		&ecostruxureit.Scanner{},
		&edamam.Scanner{},
		&edenai.Scanner{},
		&eightxeight.Scanner{},
		&elasticemail.Scanner{},
		&elevenlabsv1.Scanner{},
		&elevenlabsv2.Scanner{},
		&enablex.Scanner{},
		&endorlabs.Scanner{},
		&enigma.Scanner{},
		&envoyapikey.Scanner{},
		&eraser.Scanner{},
		&etherscan.Scanner{},
		&ethplorer.Scanner{},
		&eventbrite.Scanner{},
		&everhour.Scanner{},
		&exchangerateapi.Scanner{},
		&exchangeratesapi.Scanner{},
		&exportsdk.Scanner{},
		&extractorapi.Scanner{},
		&facebookoauth.Scanner{},
		&faceplusplus.Scanner{},
		&fastforex.Scanner{},
		&fastlypersonaltoken.Scanner{},
		&feedier.Scanner{},
		&fetchrss.Scanner{},
		&fibery.Scanner{},
		&figmapersonalaccesstokenv1.Scanner{},
		&figmapersonalaccesstokenv2.Scanner{},
		&fileio.Scanner{},
		&finage.Scanner{},
		&financialmodelingprep.Scanner{},
		&findl.Scanner{},
		&finnhub.Scanner{},
		&fixerio.Scanner{},
		&flatio.Scanner{},
		&fleetbase.Scanner{},
		&flexport.Scanner{},
		&flickr.Scanner{},
		&flightapi.Scanner{},
		&flightlabs.Scanner{},
		&flightstats.Scanner{},
		&float.Scanner{},
		&flowflu.Scanner{},
		&flutterwave.Scanner{},
		&flyio.Scanner{},
		&fmfw.Scanner{},
		&formbucket.Scanner{},
		&formcraft.Scanner{},
		&formio.Scanner{},
		&formsite.Scanner{},
		&foursquare.Scanner{},
		&frameio.Scanner{},
		&freshbooks.Scanner{},
		&freshdesk.Scanner{},
		&front.Scanner{},
		&ftp.Scanner{},
		&fulcrum.Scanner{},
		&fullstoryv1.Scanner{},
		&fullstoryv2.Scanner{},
		&fxmarket.Scanner{},
		&gcp.Scanner{},
		&gcpapplicationdefaultcredentials.Scanner{},
		&geckoboard.Scanner{},
		&gemini.Scanner{},
		// &generic.Scanner{},
		&gengo.Scanner{},
		&geoapify.Scanner{},
		&geocode.Scanner{},
		&geocodify.Scanner{},
		&geocodio.Scanner{},
		&geoipifi.Scanner{},
		// &getemail.Scanner{},
		// &getemails.Scanner{},
		&getgeoapi.Scanner{},
		&getgist.Scanner{},
		&getresponse.Scanner{},
		&getsandbox.Scanner{},
		&github_oauth2.Scanner{},
		&githubapp.Scanner{},
		&githubv1.Scanner{},
		&githubv2.Scanner{},
		&gitlabv1.Scanner{},
		&gitlabv2.Scanner{},
		&gitlabv3.Scanner{},
		&gitter.Scanner{},
		&glassnode.Scanner{},
		&gocanvas.Scanner{},
		&gocardless.Scanner{},
		&godaddyv1.Scanner{},
		&godaddyv2.Scanner{},
		&goodday.Scanner{},
		&googleoauth2.Scanner{},
		&grafana.Scanner{},
		&grafanaserviceaccount.Scanner{},
		&graphcms.Scanner{},
		&graphhopper.Scanner{},
		&groovehq.Scanner{},
		&groq.Scanner{},
		&gtmetrix.Scanner{},
		&guardianapi.Scanner{},
		&gumroad.Scanner{},
		&gyazo.Scanner{},
		&happyscribe.Scanner{},
		&harness.Scanner{},
		&harvest.Scanner{},
		&hashicorpvaultauth.Scanner{},
		&hasura.Scanner{},
		&hellosign.Scanner{},
		&helpcrunch.Scanner{},
		&helpscout.Scanner{},
		&hereapi.Scanner{},
		&heroku_v1.Scanner{},
		&heroku_v2.Scanner{},
		// &hive.Scanner{},
		&hiveage.Scanner{},
		&holidayapi.Scanner{},
		&holistic.Scanner{},
		&honeycomb.Scanner{},
		&host.Scanner{},
		&html2pdf.Scanner{},
		&hubspot_apikey_v1.Scanner{},
		&hubspot_apikey_v2.Scanner{},
		&huggingface.Scanner{},
		&humanity.Scanner{},
		&hunter.Scanner{},
		&hybiscus.Scanner{},
		&hypertrack.Scanner{},
		// &ibmclouduserkey.Scanner{},
		&iconfinder.Scanner{},
		&iexapis.Scanner{},
		&iexcloud.Scanner{},
		&imagekit.Scanner{},
		&imagga.Scanner{},
		&impala.Scanner{},
		&infura.Scanner{},
		&insightly.Scanner{},
		&instabot.Scanner{},
		&instamojo.Scanner{},
		&intercom.Scanner{},
		&interseller.Scanner{},
		&intra42.Scanner{},
		&intrinio.Scanner{},
		&invoiceocean.Scanner{},
		&ip2location.Scanner{},
		&ipapi.Scanner{},
		&ipgeolocation.Scanner{},
		&ipinfodb.Scanner{},
		&ipquality.Scanner{},
		&ipstack.Scanner{},
		&jdbc.Scanner{},
		&jiratokenv1.Scanner{},
		&jiratokenv2.Scanner{},
		&jotform.Scanner{},
		&jumpcloud.Scanner{},
		&jupiterone.Scanner{},
		&juro.Scanner{},
		&jwt.Scanner{},
		&kanban.Scanner{},
		&kanbantool.Scanner{},
		&karmacrm.Scanner{},
		&keenio.Scanner{},
		&kickbox.Scanner{},
		&klaviyo.Scanner{},
		&klipfolio.Scanner{},
		&knapsackpro.Scanner{},
		&kontent.Scanner{},
		&kraken.Scanner{},
		&kucoin.Scanner{},
		&kylas.Scanner{},
		&langfuse.Scanner{},
		&langsmith.Scanner{},
		&languagelayer.Scanner{},
		&larksuite.Scanner{},
		&larksuiteapikey.Scanner{},
		&launchdarkly.Scanner{},
		&ldap.Scanner{},
		&leadfeeder.Scanner{},
		&lemlist.Scanner{},
		&lemonsqueezy.Scanner{},
		&lendflow.Scanner{},
		&lessannoyingcrm.Scanner{},
		&lexigram.Scanner{},
		&linearapi.Scanner{},
		// &linemessaging.Scanner{},
		&linenotify.Scanner{},
		&linkpreview.Scanner{},
		&liveagent.Scanner{},
		&livestorm.Scanner{},
		&loadmill.Scanner{},
		&locationiq.Scanner{},
		&loggly.Scanner{},
		&loginradius.Scanner{},
		&logzio.Scanner{},
		&lokalisetoken.Scanner{},
		&loyverse.Scanner{},
		&lunchmoney.Scanner{},
		&luno.Scanner{},
		// &m3o.Scanner{},
		&madkudu.Scanner{},
		&magicbell.Scanner{},
		// &magnetic.Scanner{},
		&mailboxlayer.Scanner{},
		&mailchimp.Scanner{},
		&mailerlite.Scanner{},
		&mailgun.Scanner{},
		&mailjetbasicauth.Scanner{},
		&mailjetsms.Scanner{},
		&mailmodo.Scanner{},
		&mailsac.Scanner{},
		&mandrill.Scanner{},
		// &manifest.Scanner{},
		&mapbox.Scanner{},
		&mapquest.Scanner{},
		&marketstack.Scanner{},
		&mattermostpersonaltoken.Scanner{},
		&mavenlink.Scanner{},
		&maxmindlicensev1.Scanner{},
		&maxmindlicensev2.Scanner{},
		&meaningcloud.Scanner{},
		&mediastack.Scanner{},
		&meistertask.Scanner{},
		&meraki.Scanner{},
		&mesibo.Scanner{},
		&messagebird.Scanner{},
		&metaapi.Scanner{},
		&metabase.Scanner{},
		&metrilo.Scanner{},
		&microsoftteamswebhook.Scanner{},
		&mindmeister.Scanner{},
		&miro.Scanner{},
		&mite.Scanner{},
		&mixmax.Scanner{},
		// &mixpanel.Scanner{},
		&mockaroo.Scanner{},
		&moderation.Scanner{},
		&monday.Scanner{},
		&mongodb.Scanner{},
		&monkeylearn.Scanner{},
		&moonclerk.Scanner{},
		&moosend.Scanner{},
		&moralis.Scanner{},
		&mrticktock.Scanner{},
		&mux.Scanner{},
		&myfreshworks.Scanner{},
		&myintervals.Scanner{},
		// &nasdaqdatalink.Scanner{},
		&nethunt.Scanner{},
		&netlifyv1.Scanner{},
		&netlifyv2.Scanner{},
		&netsuite.Scanner{},
		&neutrinoapi.Scanner{},
		&newrelicpersonalapikey.Scanner{},
		&newsapi.Scanner{},
		&newscatcher.Scanner{},
		&nexmoapikey.Scanner{},
		&nftport.Scanner{},
		&ngc.Scanner{},
		&ngrok.Scanner{},
		&nicereply.Scanner{},
		&nightfall.Scanner{},
		&nimble.Scanner{},
		&noticeable.Scanner{},
		&notion.Scanner{},
		&nozbeteams.Scanner{},
		&npmtoken.Scanner{},
		&npmtokenv2.Scanner{},
		&nugetapikey.Scanner{},
		&numverify.Scanner{},
		&nutritionix.Scanner{},
		&nvapi.Scanner{},
		&nylas.Scanner{},
		&oanda.Scanner{},
		&okta.Scanner{},
		&omnisend.Scanner{},
		&onedesk.Scanner{},
		&onelogin.Scanner{},
		&onepagecrm.Scanner{},
		&onesignal.Scanner{},
		&onfleet.Scanner{},
		&oopspam.Scanner{},
		&openai.Scanner{},
		&opencagedata.Scanner{},
		&openuv.Scanner{},
		&openvpn.Scanner{},
		&openweather.Scanner{},
		&opsgenie.Scanner{},
		&optimizely.Scanner{},
		&overloop.Scanner{},
		&owlbot.Scanner{},
		&packagecloud.Scanner{},
		&pagarme.Scanner{},
		&pagerdutyapikey.Scanner{},
		&pandadoc.Scanner{},
		&pandascore.Scanner{},
		&paperform.Scanner{},
		&paralleldots.Scanner{},
		&parsehub.Scanner{},
		&parsers.Scanner{},
		&parseur.Scanner{},
		&partnerstack.Scanner{},
		&pastebin.Scanner{},
		&paydirtapp.Scanner{},
		&paymoapp.Scanner{},
		&paymongo.Scanner{},
		&paypaloauth.Scanner{},
		&paystack.Scanner{},
		&pdflayer.Scanner{},
		&pdfshift.Scanner{},
		&peopledatalabs.Scanner{},
		&pepipost.Scanner{},
		&percy.Scanner{},
		&photoroom.Scanner{},
		&phraseaccesstoken.Scanner{},
		&pinata.Scanner{},
		&pipedream.Scanner{},
		&pipedrive.Scanner{},
		&pivotaltracker.Scanner{},
		&pixabay.Scanner{},
		&plaidkey.Scanner{},
		&planetscale.Scanner{},
		&planetscaledb.Scanner{},
		&planviewleankit.Scanner{},
		&planyo.Scanner{},
		&plivo.Scanner{},
		&podio.Scanner{},
		&pollsapi.Scanner{},
		&poloniex.Scanner{},
		&polygon.Scanner{},
		&portainer.Scanner{},
		&portainertoken.Scanner{},
		&positionstack.Scanner{},
		&postageapp.Scanner{},
		&postbacks.Scanner{},
		&postgres.Scanner{},
		&posthog.Scanner{},
		&postman.Scanner{},
		&postmark.Scanner{},
		&powrbot.Scanner{},
		&prefect.Scanner{},
		&privacy.Scanner{},
		&privatekey.Scanner{},
		&prodpad.Scanner{},
		&prospectcrm.Scanner{},
		&protocolsio.Scanner{},
		&proxycrawl.Scanner{},
		&pubnubpublishkey.Scanner{},
		&pubnubsubscriptionkey.Scanner{},
		&pulumi.Scanner{},
		&purestake.Scanner{},
		&pushbulletapikey.Scanner{},
		&pusherchannelkey.Scanner{},
		&pypi.Scanner{},
		&qase.Scanner{},
		&qualaroo.Scanner{},
		&qubole.Scanner{},
		&rabbitmq.Scanner{},
		&railwayapp.Scanner{},
		&ramp.Scanner{},
		&rapidapi.Scanner{},
		// &raven.Scanner{},
		&rawg.Scanner{},
		&razorpay.Scanner{},
		&reachmail.Scanner{},
		&readme.Scanner{},
		&reallysimplesystems.Scanner{},
		&rebrandly.Scanner{},
		&rechargepayments.Scanner{},
		&redis.Scanner{},
		&refiner.Scanner{},
		&rentman.Scanner{},
		&repairshopr.Scanner{},
		&replicate.Scanner{},
		&replyio.Scanner{},
		&requestfinance.Scanner{},
		// &restpack.Scanner{},
		&restpackhtmltopdfapi.Scanner{},
		&restpackscreenshotapi.Scanner{},
		&revampcrm.Scanner{},
		&ringcentral.Scanner{},
		&ritekit.Scanner{},
		&roaring.Scanner{},
		&robinhoodcrypto.Scanner{},
		&rocketreach.Scanner{},
		// &rockset.Scanner{},
		&rootly.Scanner{},
		&route4me.Scanner{},
		&rownd.Scanner{},
		&rubygems.Scanner{},
		&runrunit.Scanner{},
		&saladcloudapikey.Scanner{},
		&salesblink.Scanner{},
		&salescookie.Scanner{},
		&salesflare.Scanner{},
		&salesforce.Scanner{},
		&salesforceoauth2.Scanner{},
		&salesforcerefreshtoken.Scanner{},
		&salesmate.Scanner{},
		&sanity.Scanner{},
		&satismeterprojectkey.Scanner{},
		&satismeterwritekey.Scanner{},
		&saucelabs.Scanner{},
		&scalewaykey.Scanner{},
		&scalr.Scanner{},
		&scrapeowl.Scanner{},
		&scraperapi.Scanner{},
		&scraperbox.Scanner{},
		&scrapestack.Scanner{},
		&scrapfly.Scanner{},
		&scrapingant.Scanner{},
		&scrapingbee.Scanner{},
		&screenshotapi.Scanner{},
		&screenshotlayer.Scanner{},
		&scrutinizerci.Scanner{},
		&securitytrails.Scanner{},
		&segmentapikey.Scanner{},
		&selectpdf.Scanner{},
		&semaphore.Scanner{},
		&sendbird.Scanner{},
		&sendbirdorganizationapi.Scanner{},
		&sendgrid.Scanner{},
		&sendinbluev2.Scanner{},
		&sentrytokenv1.Scanner{},
		&sentrytokenv2.Scanner{},
		&sentryorgtoken.Scanner{},
		&serphouse.Scanner{},
		&serpstack.Scanner{},
		&sheety.Scanner{},
		&sherpadesk.Scanner{},
		&shipday.Scanner{},
		&shodankey.Scanner{},
		&shopify.Scanner{},
		&shortcut.Scanner{},
		&shotstack.Scanner{},
		&shutterstock.Scanner{},
		&shutterstockoauth.Scanner{},
		&signable.Scanner{},
		&signalwire.Scanner{},
		&signaturit.Scanner{},
		&signupgenius.Scanner{},
		&sigopt.Scanner{},
		&simfin.Scanner{},
		&simplesat.Scanner{},
		&simplynoted.Scanner{},
		&simvoly.Scanner{},
		&sinchmessage.Scanner{},
		&sirv.Scanner{},
		&siteleaf.Scanner{},
		&skrappio.Scanner{},
		&skybiometry.Scanner{},
		&slack.Scanner{}, // has 4 secret types
		&slackwebhook.Scanner{},
		&smartsheets.Scanner{},
		&smartystreets.Scanner{},
		&smooch.Scanner{},
		&snipcart.Scanner{},
		&snowflake.Scanner{},
		&snykkey.Scanner{},
		&sonarcloud.Scanner{},
		&sourcegraph.Scanner{},
		&sourcegraphcody.Scanner{},
		// &sparkpost.Scanner{},
		&speechtextai.Scanner{},
		&splunkobservabilitytoken.Scanner{},
		&spoonacular.Scanner{},
		&sportsmonk.Scanner{},
		// &spotifykey.Scanner{},
		&sqlserver.Scanner{},
		&square.Scanner{},
		&squareapp.Scanner{},
		&squarespace.Scanner{},
		&squareup.Scanner{},
		&sslmate.Scanner{},
		&statuscake.Scanner{},
		&statuspage.Scanner{},
		&statuspal.Scanner{},
		&stitchdata.Scanner{},
		&stockdata.Scanner{},
		&storecove.Scanner{},
		&stormboard.Scanner{},
		&stormglass.Scanner{},
		&storyblok.Scanner{},
		&storyblokpersonalaccesstoken.Scanner{},
		&storychief.Scanner{},
		&strava.Scanner{},
		&streak.Scanner{},
		&stripe.Scanner{},
		&stripepaymentintent.Scanner{},
		&stripo.Scanner{},
		&stytch.Scanner{},
		&sugester.Scanner{},
		&sumologickey.Scanner{},
		&supabasetoken.Scanner{},
		&supernotesapi.Scanner{},
		&surveyanyplace.Scanner{},
		&surveybot.Scanner{},
		&surveysparrow.Scanner{},
		&survicate.Scanner{},
		&swell.Scanner{},
		&swiftype.Scanner{},
		&tableau.Scanner{},
		&tailscale.Scanner{},
		&tallyfy.Scanner{},
		&tatumio.Scanner{},
		&taxjar.Scanner{},
		&teamgate.Scanner{},
		&teamworkcrm.Scanner{},
		&teamworkdesk.Scanner{},
		&teamworkspaces.Scanner{},
		&technicalanalysisapi.Scanner{},
		&tefter.Scanner{},
		&telegrambottoken.Scanner{},
		&teletype.Scanner{},
		&telnyx.Scanner{},
		&terraformcloudpersonaltoken.Scanner{},
		&testingbot.Scanner{},
		&textmagic.Scanner{},
		&theoddsapi.Scanner{},
		&thinkific.Scanner{},
		&thousandeyes.Scanner{},
		&ticketmaster.Scanner{},
		&tickettailor.Scanner{},
		&tiingo.Scanner{},
		&timecamp.Scanner{},
		&timezoneapi.Scanner{},
		&tineswebhook.Scanner{},
		&tmetric.Scanner{},
		&todoist.Scanner{},
		// &toggltrack.Scanner{},
		&tokeet.Scanner{},
		&tomorrowio.Scanner{},
		&tomtom.Scanner{},
		&tradier.Scanner{},
		&transferwise.Scanner{},
		&travelpayouts.Scanner{},
		&travisci.Scanner{},
		&trelloapikey.Scanner{},
		&offensiveboarenterprise.Scanner{},
		&twelvedata.Scanner{},
		&twilio.Scanner{},
		&twilioapikey.Scanner{},
		&twist.Scanner{},
		&twitch.Scanner{},
		&twitchaccesstoken.Scanner{},
		&twitterconsumerkey.Scanner{},
		&twitterv1.Scanner{},
		&twitterv2.Scanner{},
		&tyntec.Scanner{},
		&typeformv1.Scanner{},
		&typeformv2.Scanner{},
		&typetalk.Scanner{},
		&ubidots.Scanner{},
		&uclassify.Scanner{},
		&unifyid.Scanner{},
		&unplugg.Scanner{},
		&unsplash.Scanner{},
		&upcdatabase.Scanner{},
		&uplead.Scanner{},
		&uploadcare.Scanner{},
		&uptimerobot.Scanner{},
		&upwave.Scanner{},
		&uri.Scanner{},
		&urlscan.Scanner{},
		&userflow.Scanner{},
		&userstack.Scanner{},
		&vagrantcloudpersonaltoken.Scanner{},
		&vatlayer.Scanner{},
		&vbout.Scanner{},
		&vercel.Scanner{},
		&verifier.Scanner{},
		&verimail.Scanner{},
		&veriphone.Scanner{},
		&versioneye.Scanner{},
		&viewneo.Scanner{},
		&virustotal.Scanner{},
		&visualcrossing.Scanner{},
		&voiceflow.Scanner{},
		&voicegain.Scanner{},
		&voodoosms.Scanner{},
		&vouchery.Scanner{},
		&vpnapi.Scanner{},
		&vultrapikey.Scanner{},
		&vyte.Scanner{},
		&walkscore.Scanner{},
		&weatherbit.Scanner{},
		&weatherstack.Scanner{},
		&web3storage.Scanner{},
		&webex.Scanner{},
		&webexbot.Scanner{},
		&webflow.Scanner{},
		&webscraper.Scanner{},
		&webscraping.Scanner{},
		&websitepulse.Scanner{},
		&weightsandbiases.Scanner{},
		// &wepay.Scanner{},
		&whoxy.Scanner{},
		&wistia.Scanner{},
		&wiz.Scanner{},
		&worksnaps.Scanner{},
		&workstack.Scanner{},
		&worldcoinindex.Scanner{},
		&worldweather.Scanner{},
		&xai.Scanner{},
		&wrike.Scanner{},
		&yandex.Scanner{},
		&yelp.Scanner{},
		&youneedabudget.Scanner{},
		&yousign.Scanner{},
		&youtubeapikey.Scanner{},
		// &zapierwebhook.Scanner{},
		&zendeskapi.Scanner{},
		&zenkitapi.Scanner{},
		&zenrows.Scanner{},
		&zenscrape.Scanner{},
		&zenserp.Scanner{},
		&zeplin.Scanner{},
		&zerobounce.Scanner{},
		&zerotier.Scanner{},
		&zipapi.Scanner{},
		&zipbooks.Scanner{},
		&zipcodeapi.Scanner{},
		&zipcodebase.Scanner{},
		&zohocrm.Scanner{},
		&zonkafeedback.Scanner{},
		&zulipchat.Scanner{},
	}
}

func DefaultDetectors() []detectors.Detector {
	detectorList := buildDetectorList()

	// Automatically initialize all detectors that implement
	// EndpointCustomizer and/or CloudProvider interfaces.
	for _, d := range detectorList {
		customizer, ok := d.(detectors.EndpointCustomizer)
		if !ok {
			continue
		}
		// Default to always use the cloud endpoints (if available) and the found endpoints.
		customizer.UseFoundEndpoints(true)
		customizer.UseCloudEndpoint(true)
		if cloudProvider, ok := d.(detectors.CloudProvider); ok {
			customizer.SetCloudEndpoint(cloudProvider.CloudEndpoint())
		}
	}

	return detectorList
}

func DefaultDetectorTypesImplementing[T any]() map[detectorspb.DetectorType]struct{} {
	out := make(map[detectorspb.DetectorType]struct{})
	for _, detector := range DefaultDetectors() {
		if _, ok := detector.(T); ok {
			out[detector.Type()] = struct{}{}
		}
	}
	return out
}
